### ISSUE TITLE
Update Image in graph 

### ISSUE THREAD

**Issue by fantypants** [boydm/scenic#110]
Is there a method to produce an image (in my case QR Code which is rendered to a png) and then have it displayed via the normal fill method (fill: {:img}) currently i can get it to render once but it takes ~4secs for the png to render correctly so nothing is displayed on the second attempt

Alternatively, I have the output of the QR Code as binary, is there a method to render a group of rectangles given a list? i.e i have a list:

``` [1,1,1,0]``` it should render three white squares and one black square next to it. Digging around in the core library yesterday i played with grouping etc, but i think i need a little more info for it

**Comment by boydm** [comment]
It should work in theory... but isn't an area I've really dived into yet. That is... dynamic generation of image content.

The key is to put image data of a supported format into the cache so that the renderer can use it. What in-memory image format are you generating for the QR code?

Or, if you like, what library are you using to generate the image...

**Comment by boydm** [comment]
Before diving too deep into this, please take a look at how @wstucco did it in this repo:

https://gitlab.com/wstucco/scenic-color-cycling

He is dynamically editing an image and pushing it out into the graph. Works really well.

**Comment by fantypants** [comment]
Thank you very much, I was using png, now playing with placing the rectangles and altering the color codes on a update based on the Id of the block. I'll take a gander at the above library.

**Comment by fantypants** [comment]
Thanks for that, I tweaked a few things based on the above project and it now works perfectly.
