### ISSUE TITLE
Cannot use component in scene ref

### ISSUE THREAD

**Issue by vacarsu** [boydm/scenic#173]
When trying to use a scene_ref I'm getting the following error.
```
%RuntimeError{message: "You have set a dynamic SceneRef on a graph in a scene where has_children is false"}
-->     (scenic) lib/scenic/scene.ex:1374: anonymous fn/5 in Scenic.Scene.internal_push_graph/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (scenic) lib/scenic/scene.ex:1370: Scenic.Scene.internal_push_graph/3
    (scenic) lib/scenic/scene.ex:1476: Scenic.Scene.deal_with_response_opts/2
    (scenic) lib/scenic/scene.ex:1453: Scenic.Scene.deal_with_noreply/4
    (scenic) lib/scenic/scene.ex:871: Scenic.Scene.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
```

If I remove all components and only use primitives in the referenced scene it work perfectly.

**Comment by boydm** [comment]
You need to set `has_children` to true, when you use `Scenic.Component`. Like this

`use Scenic.Component, has_children: true`

Do this in the scene where you are setting the SceneRef.

The reasoning for this is that managing referenced scenes requires traversing the graph, which is potentially time consuming. If you know you won't use scene_refs in a graph, then you can set has_children to false, which uses a faster code path at runtime.

Normally, has_children is set to true by default, so you must be using

`use Scenic.Component, has_children: false` in the declaration of the scene. Either set it to true or remove the `has_children` part of the declaration to use the default.

**Comment by boydm** [comment]
@vacarsu I'd like to know if that worked for you. Then I'll close the issue.

**Comment by vacarsu** [comment]
The thing is I'm trying to reference a Scene, not a component, inside of another scene.

**Comment by vacarsu** [comment]
Here is a reproduction of the issue I'm having. Just clone the repo, run `mix deps.get`, then `iex -S mix`.

https://github.com/vacarsu/scenic-sceneref-repro

**Comment by Eiji7** [comment]
@boydm From what I found it's a bug in `scenic` **or** at least wrong error message.

Here is how I was trying to find it:

First of all we have:
```elixir
# …
{Sceneref.Scene.ExampleScene, {nil, [name: :example_scene]}}
# …
```
which is info about a child passed to app's supervisor (`scenic-sceneref-repro/lib/sceneref.ex:13`)

**Note**: I'm not sure if such initialization is correct, but anyway it does not changing that we have bad error message.

Secondly we have this code:
```elixir
  # …
  def init({scene_module, args, opts}) do
    # …
    state = %{
      has_children: has_children,
      # …
      dynamic_children_pid: nil,
      # …
    }
    # …
```
We can see here that we are explicitly setting `dynamic_children_pid` to `nil` (`scenic/lib/scenic/scene.ex:725-787`)

However this is not the only place when we are setting `dynamic_children_pid` before we are getting this error. Here is a next part:

```elixir
  # …
  def handle_continue(
        {:__scene_init_2__, scene_module, args, opts},
        %{scene_ref: scene_ref} = state
      ) do
    # …
    {supervisor_pid, dynamic_children_pid} =
      case Process.info(supervisor_pid) do
        # …

        info ->
          case get_in(info, [:dictionary, :"$initial_call"]) do
            {:supervisor, Scene.Supervisor, _} ->
              dynamic_children_pid =
                Supervisor.which_children(supervisor_pid)
                # credo:disable-for-next-line Credo.Check.Refactor.Nesting
                |> Enum.find_value(fn
                  {DynamicSupervisor, pid, :supervisor, [DynamicSupervisor]} -> pid
                  _ -> nil
                end)

              {supervisor_pid, dynamic_children_pid}
            # …
          end
      end
    # …
```
In this case with call `get_in(info, [:dictionary, :"$initial_call"])` we have: `{:supervisor, Supervisor.Default, 1}` instead of `{:supervisor, Scene.Supervisor, 1}`. From what we can see here the only case that would work is that we need to have initializing `Sceneref.Scene.ExampleScene` under `Scene.Supervisor` instead of our app's main supervisor … is that correct? (`scenic/lib/scenic/scene.ex:800-839`)

Here is the way to final problem (all in same file i.e.: `scenic/lib/scenic/scene.ex`):
1. `{:noreply, state, {:continue, {:__scene_init_3__, scene_module, args, opts}}}` - **line**: `858`
2. `def handle_continue({:__scene_init_3__, scene_module, args, opts}, state) do` - **line**: `862`
3. `deal_with_noreply(:noreply, state, sc_state, opt)` - **line**: `871`
4. `defp deal_with_noreply(type, state, sc_state, opts \\ nil) do` - **line**: `1452`
5. `case deal_with_response_opts(opts, state) do` - **line**: `1453`
6. `defp deal_with_response_opts(opts, state) when is_list(opts) do` - **line**: `1473`
7. `%Graph{} = graph -> internal_push_graph(graph, nil, state)` - **line**: `1476`

Finally we have a function with error:
```elixir
  def internal_push_graph(
        %Graph{} = raw_graph,
        sub_id,
        %{
          has_children: true,
          scene_ref: scene_ref,
          raw_scene_refs: old_raw_refs,
          dyn_scene_pids: old_dyn_pids,
          dyn_scene_keys: old_dyn_keys,
          dynamic_children_pid: dyn_sup,
          viewport: viewport
        } = state
      ) do
    # …
          unless dyn_sup do
            raise "You have set a dynamic SceneRef on a graph in a scene where has_children is false"
          end
          # …
```
The first red light here is pattern matching: `has_children: true`. Our error still says that it's set to `false`. So the main problem (at least with understanding error message) is that the check is not about `has_children` option, but `dynamic_children_pid` which probably needs to be a pid of `Scene.Supervisor` (which is dynamic supervisor), right?

Anyway we need to add more information to that error or change it in way which would be more understandable. I found in [App Supervised Scenes](https://hexdocs.pm/scenic/scene_lifecycle.html#app-supervised-scenes) that such initialization is correct, so it looks like that's a bug in `scenic` and not only the problem with wrong message, but I'm not sure here.

**Comment by boydm** [comment]
@vacarsu and @Eiji7 

Thank you so much for the investigation! I'll dig into it too, although it may take a day or so. This whole path was pretty tricky to get right. It's behavior also subtly changed in the last version, so it is entirely possible something was missed.

Like I said, I'll dig in, but if someone had a really concise test function that replicated the error, that would be awesome.

**Comment by boydm** [comment]
@vacarsu and @Eiji7

Don't bother writing a test yet. The example you gave is really good. It will take me a little while (not too long) to wrap my head around what is happening.

**Comment by boydm** [comment]
@vacarsu  (fyi @Eiji7)

In the code where you start the example scene in your supervisor, please replace the line
`{Sceneref.Scene.ExampleScene, {nil, [name: :example_scene]}}`
with 
` {Scenic.Scene.Supervisor, {Sceneref.Scene.ExampleScene, nil, [name: :example_scene]}}`

and let me know if that works as it should.

If it does, then I have to decide whether or not to change the default child spec for a scene to point at a scene supervisor, which is only used if the scene has children. Means adding complexity to a otherwise simple part of the code.

**Comment by Eiji7** [comment]
@boydm Except 2 things after your change it works i.e. I do not have any error in console and "something" was rendered. I was a bit confused at start, because buttons did not had a good `translate` and it simply does not looks best. Last thing to note is that there were 2 `unused …` (alias and import) warnings. Anyway those 2 things needs to be fixed in example app and not in any of its dependencies.

Just found that there is already a function in `scenic` which works with such argument:
```elixir
Scenic.Scene.Supervisor.child_spec({Sceneref.Scene.ExampleScene, nil, name: :example_scene})
```

**Comment by vacarsu** [comment]
@boydm that fixed the issue.

**Comment by vacarsu** [comment]
With scene_ref remove in v0.11 closing this issue.
