### ISSUE TITLE
Is this project stalled?

### ISSUE THREAD

**Issue by cboebel** [boydm/scenic#205]
Checked in to look at issues and maybe fix some, but won't if it's not moving forward.

**Comment by Eiji7** [comment]
I don't think so. Looks like @boydm is really busy and don't update himself this project often. Instead he mostly discuss and merges PRs.

Issues and PRs are obviously welcome. If remember correctly @boydm would be happy to discuss about improvements in `C` code of `scenic_driver_glfw`.

I don't have much time as well, but will try to help as much as possible. I would be especially interested if you want to fix resizing problem, so feel free to ping me.

**Comment by boydm** [comment]
Hey guys. @Eiji7. I've been focused on a related project (https://kry10.com/blog/kry10_secure_platform) that is WAY TOO HARD and has taken a lot of my time.

I am hoping to do a pretty major update to Scenic in 2021. But the shape of it depends on how the OS comes together. Specifically, I know I need to update the cache mechanism and the way the drivers compile render scripts for graphs.

More than happy to take bug fixes and clean up and push updates as they make sense.

Also if you, or anyone else, are interested, I'd be happy to do a video call to discuss roadmap and design.

**Comment by boydm** [comment]
Areas I know I want to rework and may even involve breaking changes:

The cache, especially the way dynamic cache items are handled.
Some of the styles. Especially image fills.
The Path primitive needs to be revisited. Super powerful, but I worry not general enough.
Rename Scenic.Sensors to Scenic.PubSub
Input focus management
and quite a bit more.
Support for the Raspberry Pi 4

Nobody is yelling at me to get these these things done tho, so that indicates it is mostly used in hobby scenarios. That will eventually change, but for now it means then pressure to do the bigger items is fairly low.

**Comment by grahamhay** [comment]
Boyd,


I would very much like to participate in any video call on the Scenic roadmap/design.


Graham Hay

**Comment by boydm** [comment]
Hi Graham.
We'll do a video chat either way...   ;)

Last thought for anybody listening: Scenic has been out there for a while now. If I were to do a bigger design update on it (Not going to be this month or next... expectation setting...) Think about what you would change. I was also learning Elixir as I built it so now, I look at it and see design patterns that probably need updating.

So... I'm open to general ideas and feedback.

**Comment by Eiji7** [comment]
> Nobody is yelling at me to get these these things done tho, so that indicates it is mostly used in hobby scenarios. That will eventually change, but for now it means then pressure to do the bigger items is fairly low.

Well … nobody is yelling only because we have such an amazing community. :smiling_imp: 

Actually people are interested in using `scenic` in serious apps. From what I know right now people see that you are trying best, but also they are worried that their effort would not be worth in long term i.e. people are looking if `scenic` project would die "sooner or later" or if you are going to push it forward.

I have already worked in one of my jobs on `scenic`-based `GUI` application. However because of it's current state it was like a demo/preview app to check if we can do it. We decided to start work on `scenic` as it was really easy to work on it and meanwhile we were updating standard `web` application based on our work on `scenic`.

Also I'm one of many EF members who are watching for progress of `scenic`. If you are going to do an major update this year then `scenic` may gain much more attention. Regarding video call it would be amazing, but for now I'm in really bad situation and simply can't promise anything. For now I'm limited to EF and github.

**Comment by crertel** [comment]
@boydm I'd be down for a call. 

Maybe we should put together an agenda or sketched roadmap, or maybe have everybody bring their pet concerns?

(For example, I had some questions about specifying ST and tiling a year or two ago, and I recall a bunch of discussion--without resolution--around XB360 controller support.)

**Comment by boydm** [comment]
@Eiji7 Fair points!

It's also true that Scenic is not 1.0 for good reason. Too many rough edges. @cretel - tiling is interesting, but comes after making sure the core model is nice and smooth. (games still aren't the design point)

**Comment by crertel** [comment]
Sure, just using those as examples!

**Comment by cboebel** [comment]
Excellent. Thanks for the update. I'll go thru some issues and attempt to dig in.

**Comment by axelson** [comment]
I'd be interested in participating on a call as well (although if the participant list is getting unwieldy I'm fine sitting out). Also pinging @BWheatie since he might be interested.

**Comment by rkenzhebekov** [comment]
I am also interested to listen about scenic roadmap

**Comment by boydm** [comment]
So I've been deep in Scenic code the past week or so. Its funny how taking a break from something gives fresh perspective when you return.

I need a bit more time to crystalize my opinions, but I already know I want to dramatically change the interface between the Viewport and Drivers. Will be much simpler.

There will be some breaking changes up at the Scene level. For example, Sectors and arcs should be defined by just a radius and angle instead of radius, start_angle, end_angle. The start/end angles is really just expressing a rotation, which can be done with a rotate transform.

Also going to deprecate the Path primitive and replace it with something more directly related to the new Viewport/Driver interface. Still working on the details.

So... If any of you have strong opinions or wish some parts were different, the next month or two is the time to suggest them. The next release will definitely have breaking changes in it.

**Comment by boydm** [comment]
Here is another change I'm considering that I'd like feedback on.

Some of the primitives (`Line, Triangle, Quad`) explicitly specify the positions of all their points. But other Primitives (`Rectangle, RoundedRectangle, Circle`, etc...) Draw from the origin and then rely on transforms to move them to their final position.

I'm thinking of changing `Line`, `Triangle`, and `Quad` to work more like the others. This would make the API more consistent. For example, `Line` would then just take a single `x, y `pair and draw a line from `0, 0` to the specified position. You would then use `:translate` to move it to the correct position.

Thoughts/Objections?

**Comment by Eiji7** [comment]
@boydm My first suggestion would be to create a separate issue for such discussion. :slightly_smiling_face: 

I suggest to create a first topic like:

Title: `Refactor Scenic - new ideas welcome`

---

PRs welcome:

- [ ] Do something
Link to related comment or issue describing idea

Needs discussion:

- [ ] Do something else
Optionally link to related issue for a longer discussion

**Comment by boydm** [comment]
Right. Good call.

**Comment by boydm** [comment]
Closing. as this is indeed an active project. Was just taking a snooze.
